import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Future Markt',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<div className='relative w-full h-[100vh] select-none overflow-x-hidden xl:overflow-auto'>
					<div className="w-full h-[100vh] bg-[url('/background.jfif')] bg-cover absolute blur-lg -z-20"></div>
					<div className='absolute bg-[#07315db9] w-full h-[100vh] select-none -z-10 flex justify-center'>
						<div className='w-[95%] xl:w-[1220px] 2xl:w-[1320px] border-l border-r border-l-[#ffffff1b] border-r-[#ffffff1b] flex relative'>
							<div className='absolute left-[172px] xl:left-[336px] 2xl:left-[420px] h-full border-l border-[#ffffff1b]'></div>
							<div className='absolute right-[90px] xl:right-[430px] 2xl:right-[450px] h-full border-l border-[#ffffff1b]'></div>
						</div>
					</div>
					<div className='mx-[20px] text-white'>{children}</div>
				</div>
			</body>
		</html>
	)
}
